apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Looty/todo-list-charts.git
    targetRevision: HEAD
    path: cert-manager/
  destination:
    server: https://kubernetes.default.svc
    namespace: default #cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    # syncOptions:
    # - CreateNamespace=true