apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Looty/todo-list-charts.git
    targetRevision: HEAD
    path: kibana/
    helm:
      # # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      # parameters:
      # - name: "elasticsearch\\.enabled"
      #   value: "false"
      # - name: "elasticsearch\\.external\\.hosts[0]"
      #   value: elasticsearch-coordinating-only.logging.svc.cluster.local
      # - name: "elasticsearch\\.external\\.port"
      #   value: "9200"

      # Values file as block file
      values: |
        elasticsearch:
          enabled: false
          external: /
          hosts:
            - elasticsearch-coordinating-only.logging.svc.cluster.local
          port: 9200

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true